export const ProfileData = {
  experiences: [
    {
      company: "Automattic",
      role: "Senior Software Engineer",
      startDate: "08/2022",
      endDate: "04/2025",
      location: "",
      logo: "/a8c_white.svg",
      technologies: [
        "React",
        "TypeScript",
        "JavaScript",
        "Puppeteer",
        "Playwright",
        "SCSS",
        "PHP",
        "WordPress",
        "MySQL",
      ],
      description: [
        "Built and maintained frontend features for WooCommerce.com using React, TypeScript, JavaScript, Puppeteer, Playwright, SCSS, PHP, and WordPress",
        "Developed responsive and accessible UI components for a global eCommerce audience",
        "Contributed to architectural planning and decisions for new plugin integrations and page optimizations, webpack tuning and SEO improvements",
        "Collaborated with design, content teams, and stakeholders to implement dynamic blog and landing pages, and developed automated tools for marketing",
      ],
      achievements: [
        "Led UI redesign for WooCommerce Blog, resulting in a 47% increase in average active time and 15% growth in pageviews",
        "Contributed heavily to Core Web Vitals improvements, including bundle/code splitting, lazy loading, font loading, and Webpack tuning, which significantly improved SEO performance for almost 5000 urls",
        "Integrated automated marketing email system for WooCommerce Marketplace improving email delivery by 90%",
      ],
    },
    {
      company: "Comcast",
      role: "Software Engineer IV",
      startDate: "10/2019",
      endDate: "08/2022",
      location: "",
      logo: "/comcast.svg",
      technologies: [
        "React",
        "JavaScript",
        "Jest",
        "Enzyme",
        "Node.js",
        "GraphQL",
        "Grafana",
        "AWS",
        "Golang",
        "MongoDB",
      ],
      description: [
        "Built real-time dashboards using React, JavaScript, Jest, Enzyme, Node.js, GraphQL, Grafana and AWS to monitor infrastructure health, visualize poller uptimes, and track system metrics in real-time",
        "Rewrote backend services from scratch in Golang and GraphQL, replacing Node.js to improve runtime performance, reduce latency, and leverage Go's lightweight concurrency model",
        "Engineered a telemetry polling system with 99.7% uptime, built from the ground up in Go, to continuously collect and stream large-scale device data to AWS S3",
        "Integrated APIs with platform services and helped plan component architecture across services",
      ],
      achievements: [
        "Led development of backend services in Golang, replacing Node.js to reduce latency, improve runtime efficiency, and cut infrastructure costs by 35%",
        "Acted as DRI for high-impact feature releases, collaborating cross-functionally and delivering on tight deadlines",
      ],
    },
    {
      company: "Altimetrik",
      role: "Senior Software Engineer",
      startDate: "12/2017",
      endDate: "09/2019",
      location: "",
      logo: "/comcast.svg",
      technologies: [
        "React",
        "TypeScript",
        "Jest",
        "Enzyme",
        "SCSS",
        "Node.js",
        "MongoDB",
      ],
      description: [
        "Worked on full-stack tools for internet service capacity management using React, TypeScript, Jest, Enzyme, SCSS, Node.js, and MongoDB",
        "Created modular UI with responsive layouts and reusable design systems",
        "Developed and maintained RESTful APIs and database schemas",
      ],
      achievements: [
        "Ensured responsive design and accessibility standards across all major releases and front-end implementations",
        "Regularly made architectural decisions that improved performance, scalability, and long-term maintainability",
      ],
    },
    {
      company: "Infosys",
      role: "Senior System Engineer",
      startDate: "06/2014",
      endDate: "12/2017",
      location: "",
      logo: "/infosys.svg",
      technologies: ["Java", "BackboneJS", "HandlebarsJS", "SpringBoot"],
      description: [
        "Delivered backend solutions for Banking and telecom projects using Java, BackboneJS, and MySQL",
      ],
    },
  ],
  skills: {
    testing: ["Playwright", "Jest", "Enzyme"],
    backend: ["WordPress", "Go", "PHP", "Node.js", "Java"],
    frontend: [
      "React",
      "TypeScript",
      "JavaScript",
      "HTML",
      "CSS",
      "SCSS",
      "BackboneJS",
    ],
    database: ["MongoDB", "MySQL", "ScyllaDB"],
    devops: ["AWS", "Grafana", "CircleCI", "Concourse"],
  },
  education: {
    degree: "Bachelor of Science, Computer Science",
    institution: "KCG College of Technology, Chennai",
    graduationDate: "06/2014",
  },
};
